#!/bin/bash

#SBATCH --job-name=d2q9-bgk-vector-perf
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=1
#SBATCH --time=00:10:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COMS031424
#SBATCH --output=d2q9-bgk.out
#SBATCH --exclusive 

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
echo "vvvvvvvvvvvv 128x128 vvvvvvvvvvvv"
./d2q9-bgk ../input/input_128x128.params ../input/obstacles_128x128.dat
echo "vvvvvvvvvvvv 128x256 vvvvvvvvvvvv"
./d2q9-bgk ../input/input_128x256.params ../input/obstacles_128x256.dat
echo "vvvvvvvvvvvv 256x256 vvvvvvvvvvvv"
./d2q9-bgk ../input/input_256x256.params ../input/obstacles_256x256.dat
echo "vvvvvvvvvvvv 1024x1024 vvvvvvvvvvvv"
./d2q9-bgk ../input/input_1024x1024.params ../input/obstacles_1024x1024.dat
